# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  buildConfiguration: 'Release'



stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: dotnet restore src/Tripello.Server.Web
      displayName: 'Restore dependencies'

    - script: dotnet build --configuration $(buildConfiguration) src/Tripello.Server.Web
      displayName: '$(buildConfiguration) build'

- stage: BuildAndPublishImage
  displayName: Build and publish image
  jobs:
  - job: BuildAndPublish
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          '$(tag)'
          'latest'

    - task: Docker@2
      displayName: Log in to Docker Hub
      inputs:
        containerRegistry: 'DockerHub-mattwatson1'
        command: 'login'

    - task: Docker@2
      displayName: Push the image to Docker Hub
      inputs:
        containerRegistry: 'DockerHub-mattwatson1'
        repository: 'tripello'
        command: 'push'
        tags: '$(tag)'