# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

resources:
- repo: self

variables:
  dockerId: mattwatson1
  imageName: tripello
  tag: '$(Build.BuildNumber)'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: dotnet restore src/Tripello.Server.Web
      displayName: 'Restore dependencies'

    - script: dotnet build --configuration $(buildConfiguration) src/Tripello.Server.Web
      displayName: '$(buildConfiguration) build'

- stage: BuildAndPublishImage
  displayName: Build and publish image
  jobs:
  - job: BuildAndPublish
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # Manual command because Docker@2 didn't want to tag my image =(
    - script: docker build -t $(dockerId)/$(imageName):$(tag) .
      displayName: 'Docker Build'

    - task: Docker@2
      displayName: Log in to Docker Hub
      inputs:
        containerRegistry: 'DockerHub-mattwatson1'
        command: 'login'

    # Manual command because Docker@2 didn't want to find my image =(
    - script: docker push $(dockerId)/$(imageName):$(tag)
      displayName: 'Docker Push'